site_name: VIEPS introduction to python
site_author: Louis Moresi
site_dir: www

pages:
- Home: index.md
- Site Map: SiteMap.md
- Sections:
    - "1 - Introduction": Introduction.md
    - "2 - Tutorials": Tutorials.md

- Help:
    - HelpMe.md
# Other:
#     - Exercises.md
#     - Mathing.md

## Here is how to add extra (external) links to the navigation bar
##
## 1) Add a link to the nav bar
##     The item you add is a two-member list: ["Name for the link", "url"]
## 2) Add a new menu item to the nav bar
##     The item you add is a three-or-more-member list with a name for the menu item as the first member
##     and subsequent entries being lists of names / urls as above:
##     [ "Menu name", ["Menu item 1 name", "Menu item 1 url"], ["Menu item 2 name", "Menu item 2 url"], ... ]
##

extra:
    nav_links:
        - ["Live Content",
            ["Notebooks", "/notebooks/Notebooks" ],
            ["Terminal", "/terminals/1" ],
            ["Console",  "/tree/Notebooks#running" ]
          ]
        - "Help": HelpMe.md

        # - ["Assessment",
        #     ["Assessment 1", "/notebooks/Notebooks/ForAssessment/Exercise1.ipynb"],
        #     ["Assessment 2", "/notebooks/Notebooks/ForAssessment/Exercise2.ipynb"],
        #     ["Assessment 3", "/notebooks/Notebooks/ForAssessment/Exercise3.ipynb"],
        #     ["Assessment 4", "/notebooks/Notebooks/Numpy/GameOfLife.ipynb"],
        #     ["Assessment 5", "/notebooks/Notebooks/Numpy/Seasonal_averages.ipynb"]
        #   ]



# theme over-ride

theme_dir: jupyter-server-theme

# Layout of pages

use_directory_urls: False
include_next_prev: False

# Theme
theme: flatly

# Mathematics

markdown_extensions:
   # other extensions ...
   - pymdownx.arithmatex

# other settings ...

extra_javascript:
  # other extra java script
  - js/mathjax-local-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
