{% set name = "quagmire" %}
{% set version = "0.9.7b0" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - meson-python
    - numpy >=1.16
  host:
    - python
    - petsc4py
    - h5py
    - meson-python
  run:
    - python
    - numpy
    - scipy
    - stripy
    - petsc4py
    - mpi4py
    - h5py
    - pint
    - fs
    - fs.webdavfs


test:
  requires:
    - pytest 

  source_files:
      - tests

  commands:
#    - pytest - TODO fix all tests. Now now just leave test_2 in
    - pytest tests/test_2_mesh_variables.py

about:
  home: "https://github.com/underworldcode/quagmire"

extra:
  recipe-maintainers:
    - jgiordani
    - lmoresi
    - brmather
    - rbeucher
